

export const metadata = {
  title: "Contact",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>Welcome to Contact Page{children}</body>
    </html>
  );
}